### ISSUE TITLE
Upgrading to 3.4.15 breaks basic auth

### ISSUE THREAD

**Issue by ryaan-anthony** [workarea-commerce/workarea-basic-auth#2]
**Describe the bug**
The error is raised when running admin tests:
```
NameError: uninitialized constant Rack::Attack::ALERT_LOGIC_IP_ADDRESSES
workarea-basic_auth-1.1.1/config/initializers/access_control.rb:18
```

**Workarea Setup (please complete the following information):**
 - Workarea Version: 3.4.15
 - workarea-basic_auth-1.1.1

**Comment by tubbo** [comment]
this will be resolved in the next patch of basic-auth. https://github.com/workarea-commerce/workarea-basic-auth/pull/1

make sure you look through past PRs before opening an issue :)
